import { defineConfig, type DefaultTheme } from 'vitepress'
import { tabsMarkdownPlugin } from 'vitepress-plugin-tabs'
import githubAlertsPlugin from './plugins/githubAlertsPlugin'
import youtubeEmbedPlugin from './plugins/youtubeEmbedPlugin'
import lineNumberPlugin from './plugins/lineNumbers'
import inlineCodeVPre from './plugins/inlineCodeVPre'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

// Generated by `npm run import` from the Obsidian Digital Garden vault.
const navigation = JSON.parse(
    readFileSync(fileURLToPath(new URL('./navigation.json', import.meta.url)), 'utf-8')
) as {
    nav: DefaultTheme.NavItem[]
    sidebar: DefaultTheme.SidebarItem[]
}

// https://vitepress.dev/reference/site-config
export default defineConfig({
    title: 'M0B Notes',
    srcDir: 'src',
    description: 'Notas técnicas de pentesting, red team y seguridad ofensiva de Darío Pérez (M0B)',
    cleanUrls: true,
    lastUpdated: true,
    ignoreDeadLinks: true,
    appearance: 'force-dark',
    sitemap: {
        hostname: 'https://imm0b.github.io'
    },
    head: [
        ['link', { rel: 'icon', type: 'image/svg+xml', href: '/images/m0b2.svg' }],
        ['link', { rel: 'alternate icon', type: 'image/png', href: '/images/m0b.png' }],
        ['link', { rel: 'apple-touch-icon', href: '/images/m0b.png' }],
        ['meta', { name: 'theme-color', content: '#000000' }],
        ['meta', { name: 'color-scheme', content: 'dark' }],
        [
            'link',
            {
                rel: 'stylesheet',
                href: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,1,0'
            }
        ]
    ],
    transformHead: ({ pageData }) => {
        const pageTitle = pageData.title ? `${pageData.title} | M0B Notes` : 'M0B Notes'
        const pageDescription =
            pageData.description ||
            'Notas técnicas de pentesting, red team y seguridad ofensiva de Darío Pérez (M0B)'
        return [
            ['meta', { property: 'og:title', content: pageTitle }],
            ['meta', { property: 'og:description', content: pageDescription }],
            ['meta', { name: 'twitter:title', content: pageTitle }],
            ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
            ['meta', { name: 'twitter:description', content: pageDescription }]
        ]
    },
    themeConfig: {
        search: {
            provider: 'local'
        },
        nav: navigation.nav,
        outline: 'deep',
        sidebar: navigation.sidebar,
        socialLinks: [
            { icon: 'github', link: 'https://github.com/ImM0B' },
            { icon: 'linkedin', link: 'https://www.linkedin.com/in/dar%C3%ADo-p%C3%A9rez/' },
            { icon: 'youtube', link: 'https://www.youtube.com/@dariooperez' }
        ],
        docFooter: {
            prev: 'Anterior',
            next: 'Siguiente'
        },
        darkModeSwitchLabel: 'Tema',
        sidebarMenuLabel: 'Menú',
        returnToTopLabel: 'Volver arriba',
        outlineTitle: 'En esta página',
        lastUpdatedText: 'Actualizado',
        footer: {
            message: 'Notas personales de seguridad ofensiva.',
            copyright: 'Darío Pérez Ballesteros — M0B'
        }
    },
    markdown: {
        config(md) {
            md.use(tabsMarkdownPlugin)
            md.use(githubAlertsPlugin)
            md.use(youtubeEmbedPlugin)
            md.use(lineNumberPlugin)
            md.use(inlineCodeVPre)
        }
    }
})
